version: '3.8'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    command: server --console-address ":9001" /data
    env_file:
      - .env
    restart: always

  model:
    build:
      context: ../
      dockerfile: demo_test/Dockerfile
    container_name: model
    volumes:
      - ../clay/python:/app/clay/python
    env_file:
      - .env

networks:
  app-network: 
    driver: bridge
volumes:
  minio_storage: