[tool.isort]
known_first_party = [
    "demo-test"
]
include_trailing_comma = "True"
multi_line_output = 3
skip = ["third_party", "__init__.py"]
skip_gitignore = "True"
use_parentheses = "True"
profile = "black"
line_length = 100

[tool.black]
line-length = 100

[tool.mypy]
exclude = ["env", "tests", "build", "tmp", "notebooks", "mkdocs", "gitlab", "scripts"]
files = ["src"]
install_types = "True"
non_interactive = "True"
disallow_untyped_defs = "True"
show_error_codes = "True"
warn_redundant_casts = "True"
warn_unused_configs = "True"
warn_unused_ignores = "False"
allow_redefinition = "True"
disable_error_code = "attr-defined"
warn_no_return = "False"

[tool.pytest.ini_options]
pythonpath = [
  ".", "demo-test"
]
