name: Run Benchmarks

on:
  workflow_dispatch:
    inputs:
      benchmark-id:
        description: "Give any id which will identify this benchmarking uniquely"
        required: true
      mem-limits:
        description: "Memory limit for the pod in Mi unit"
        required: true
      cpu-limits:
        description: "Cpu limit for the pod in m unit"
        required: true
      docker-block-image-tag:
        description: "Image tag which will be used for benchmarking"
        required: true
      input-file-directory-path:
        required: false
        default: "./tests/benchmark/inputs"

env:
  AWS_DEFAULT_REGION: us-east-2

permissions:
  id-token: write
  contents: read

jobs:
  run_benchmarks:
    runs-on: [pixxel-default]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::352963465703:role/GithubDeployRole
          audience: https://github.com/pixxelhq
          aws-region: ${{ env.AWS_DEFAULT_REGION }} 
      - name: Checkout
        uses: actions/checkout@v2
      - name: run mbench
        uses: pixxelhq/mbench@feat/testing-custom-github-actions
        with:
          id: ${{ github.event.inputs.benchmark-id }}
          mem-limits: ${{ github.event.inputs.mem-limits }}
          cpu-limits: ${{ github.event.inputs.cpu-limits }}
          docker-block-image-url: "269716152256.dkr.ecr.us-east-2.amazonaws.com/demo_test:${{ github.event.inputs.docker-block-image-tag }}"
          block-name: "demo_test"
          input-file-directory-path: ${{ github.event.inputs.input-file-directory-path }}