name: "Build model"

on:
  workflow_dispatch

permissions:
    id-token: write
    contents: read

jobs:
  building-test-docker:
    runs-on: [pixxel-default]
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::269716152256:role/GithubActionsRole
          audience: sigstore
          aws-region: us-east-2

      - name: Set aws codeartifact token for clay
        id: codeartifact-token
        run: |
          echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain p-core-artifactory-domain-01 --domain-owner 269716152256 --query authorizationToken --region us-east-2 --output text)" >> "$GITHUB_ENV"

      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build --secret id=CODEARTIFACT_AUTH_TOKEN,env=${{ secrets.CODEARTIFACT_AUTH_TOKEN }} --tag modeltest .
